### ISSUE TITLE
⚠️ The `save-state` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by chrisedebo** [yogeshlonkar/trivy-cache-action#45]
Hi there, 

We use this trivy-cache-action in our workflows. Great stuff, thanks for developing it. 

Since we introduced it we are seeing warnings similar to the title of this issue. I can see that you have updated your packages-lock.json file in the main branch but the latest release doesn't have the update to the core package.

Can you make a new release?

Cheers

Chris

**Comment by yogeshlonkar** [comment]
Fixed in [v0.1.3](https://github.com/yogeshlonkar/trivy-cache-action/releases/tag/v0.1.3). Floating tag v0 also points to this release.
